global: {}

ibm-platform-navigator-instance:
  ibmplatformnavigator:
    name: integration-navigator
    spec:
      license:
        accept: true
        license: L-JTPV-KYG8TF
      mqDashboard: true
      version: 16.1.0
      replicas: 2   
